# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None):  # noqa: E501
        """UserId - a model defined in Swagger

        :param user_id: The user_id of this UserId.  # noqa: E501
        :type user_id: int
        """
        self.swagger_types = {
            'user_id': int
        }

        self.attribute_map = {
            'user_id': 'user_id'
        }
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_id of this UserId.  # noqa: E501
        :rtype: UserId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this UserId.


        :return: The user_id of this UserId.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this UserId.


        :param user_id: The user_id of this UserId.
        :type user_id: int
        """

        self._user_id = user_id
