/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Comment} from './model/Comment';
import {Movie} from './model/Movie';
import {MovieId} from './model/MovieId';
import {Review} from './model/Review';
import {ShowId} from './model/ShowId';
import {Title} from './model/Title';
import {Tvshow} from './model/Tvshow';
import {User} from './model/User';
import {UserIdBioBody} from './model/UserIdBioBody';
import {UserIdInterestsBody} from './model/UserIdInterestsBody';
import {UserIdPasswordBody} from './model/UserIdPasswordBody';
import {UserIdPfpBody} from './model/UserIdPfpBody';
import {UserIdUsernameBody} from './model/UserIdUsernameBody';
import {UserSigninBody} from './model/UserSigninBody';
import {UserSignupBody} from './model/UserSignupBody';
import {ReviewsApi} from './api/ReviewsApi';
import {TitlesApi} from './api/TitlesApi';
import {UserApi} from './api/UserApi';

/**
* A_website_for_movies_and_TV_shows_reviews.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Fmd = require('index'); // See note below*.
* var xxxSvc = new Fmd.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Fmd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Fmd.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Fmd.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 3.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Comment model constructor.
     * @property {module:model/Comment}
     */
    Comment,

    /**
     * The Movie model constructor.
     * @property {module:model/Movie}
     */
    Movie,

    /**
     * The MovieId model constructor.
     * @property {module:model/MovieId}
     */
    MovieId,

    /**
     * The Review model constructor.
     * @property {module:model/Review}
     */
    Review,

    /**
     * The ShowId model constructor.
     * @property {module:model/ShowId}
     */
    ShowId,

    /**
     * The Title model constructor.
     * @property {module:model/Title}
     */
    Title,

    /**
     * The Tvshow model constructor.
     * @property {module:model/Tvshow}
     */
    Tvshow,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserIdBioBody model constructor.
     * @property {module:model/UserIdBioBody}
     */
    UserIdBioBody,

    /**
     * The UserIdInterestsBody model constructor.
     * @property {module:model/UserIdInterestsBody}
     */
    UserIdInterestsBody,

    /**
     * The UserIdPasswordBody model constructor.
     * @property {module:model/UserIdPasswordBody}
     */
    UserIdPasswordBody,

    /**
     * The UserIdPfpBody model constructor.
     * @property {module:model/UserIdPfpBody}
     */
    UserIdPfpBody,

    /**
     * The UserIdUsernameBody model constructor.
     * @property {module:model/UserIdUsernameBody}
     */
    UserIdUsernameBody,

    /**
     * The UserSigninBody model constructor.
     * @property {module:model/UserSigninBody}
     */
    UserSigninBody,

    /**
     * The UserSignupBody model constructor.
     * @property {module:model/UserSignupBody}
     */
    UserSignupBody,

    /**
    * The ReviewsApi service constructor.
    * @property {module:api/ReviewsApi}
    */
    ReviewsApi,

    /**
    * The TitlesApi service constructor.
    * @property {module:api/TitlesApi}
    */
    TitlesApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
