/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Fmd);
  }
}(this, function(expect, Fmd) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Comment', function() {
      beforeEach(function() {
        instance = new Fmd.Comment();
      });

      it('should create an instance of Comment', function() {
        // TODO: update the code to test Comment
        expect(instance).to.be.a(Fmd.Comment);
      });

      it('should have the property commentId (base name: "comment_id")', function() {
        // TODO: update the code to test the property commentId
        expect(instance).to.have.property('commentId');
        // expect(instance.commentId).to.be(expectedValueLiteral);
      });

      it('should have the property reviewId (base name: "review_id")', function() {
        // TODO: update the code to test the property reviewId
        expect(instance).to.have.property('reviewId');
        // expect(instance.reviewId).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "user_id")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property content (base name: "content")', function() {
        // TODO: update the code to test the property content
        expect(instance).to.have.property('content');
        // expect(instance.content).to.be(expectedValueLiteral);
      });

    });
  });

}));
