/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Fmd);
  }
}(this, function(expect, Fmd) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Title', function() {
      beforeEach(function() {
        instance = new Fmd.Title();
      });

      it('should create an instance of Title', function() {
        // TODO: update the code to test Title
        expect(instance).to.be.a(Fmd.Title);
      });

      it('should have the property movie (base name: "movie")', function() {
        // TODO: update the code to test the property movie
        expect(instance).to.have.property('movie');
        // expect(instance.movie).to.be(expectedValueLiteral);
      });

      it('should have the property tvshow (base name: "tvshow")', function() {
        // TODO: update the code to test the property tvshow
        expect(instance).to.have.property('tvshow');
        // expect(instance.tvshow).to.be(expectedValueLiteral);
      });

    });
  });

}));
