/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Fmd);
  }
}(this, function(expect, Fmd) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Fmd.ReviewsApi();
  });

  describe('(package)', function() {
    describe('ReviewsApi', function() {
      describe('reviewPost', function() {
        it('should call reviewPost successfully', function(done) {
          // TODO: uncomment, update parameter values for reviewPost call
          /*

          instance.reviewPost(movieId, showId, userId, rating, title, content, creationTime, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('reviewReviewIdCommentGet', function() {
        it('should call reviewReviewIdCommentGet successfully', function(done) {
          // TODO: uncomment, update parameter values for reviewReviewIdCommentGet call and complete the assertions
          /*

          instance.reviewReviewIdCommentGet(reviewId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Fmd.Comment);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('reviewReviewIdCommentPost', function() {
        it('should call reviewReviewIdCommentPost successfully', function(done) {
          // TODO: uncomment, update parameter values for reviewReviewIdCommentPost call and complete the assertions
          /*

          instance.reviewReviewIdCommentPost(reviewId, userId, content, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Fmd.Comment);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('reviewReviewIdLikesPut', function() {
        it('should call reviewReviewIdLikesPut successfully', function(done) {
          // TODO: uncomment, update parameter values for reviewReviewIdLikesPut call
          /*

          instance.reviewReviewIdLikesPut(reviewId, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('reviewTitleIdGet', function() {
        it('should call reviewTitleIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for reviewTitleIdGet call and complete the assertions
          /*
          var opts = {};

          instance.reviewTitleIdGet(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Fmd.Review);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('reviewUserUserIdGet', function() {
        it('should call reviewUserUserIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for reviewUserUserIdGet call and complete the assertions
          /*
          var opts = {};

          instance.reviewUserUserIdGet(userId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Fmd.Review);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
