/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Comment model module.
 * @module model/Comment
 * @version 3.0.0
 */
export class Comment {
  /**
   * Constructs a new <code>Comment</code>.
   * @alias module:model/Comment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Comment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Comment} obj Optional instance to populate.
   * @return {module:model/Comment} The populated <code>Comment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Comment();
      if (data.hasOwnProperty('comment_id'))
        obj.commentId = ApiClient.convertToType(data['comment_id'], 'Number');
      if (data.hasOwnProperty('review_id'))
        obj.reviewId = ApiClient.convertToType(data['review_id'], 'Number');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} commentId
 */
Comment.prototype.commentId = undefined;

/**
 * @member {Number} reviewId
 */
Comment.prototype.reviewId = undefined;

/**
 * @member {Number} userId
 */
Comment.prototype.userId = undefined;

/**
 * @member {String} content
 */
Comment.prototype.content = undefined;

