/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MovieId model module.
 * @module model/MovieId
 * @version 3.0.0
 */
export class MovieId {
  /**
   * Constructs a new <code>MovieId</code>.
   * @alias module:model/MovieId
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MovieId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MovieId} obj Optional instance to populate.
   * @return {module:model/MovieId} The populated <code>MovieId</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MovieId();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
MovieId.prototype.id = undefined;

