/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MovieId} from './MovieId';
import {ShowId} from './ShowId';

/**
 * The Review model module.
 * @module model/Review
 * @version 3.0.0
 */
export class Review {
  /**
   * Constructs a new <code>Review</code>.
   * @alias module:model/Review
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Review</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Review} obj Optional instance to populate.
   * @return {module:model/Review} The populated <code>Review</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Review();
      if (data.hasOwnProperty('review_id'))
        obj.review_id = ApiClient.convertToType(data['review_id'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('movie_id'))
        obj.movie_id = MovieId.constructFromObject(data['movie_id']);
      if (data.hasOwnProperty('show_id'))
        obj.show_id = ShowId.constructFromObject(data['show_id']);
      if (data.hasOwnProperty('user_id'))
        obj.user_id = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('likes'))
        obj.likes = ApiClient.convertToType(data['likes'], {'String': 'Boolean'});
      if (data.hasOwnProperty('rating'))
        obj.rating = ApiClient.convertToType(data['rating'], 'Number');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('creation_time'))
        obj.creation_time = ApiClient.convertToType(data['creation_time'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} review_id
 */
Review.prototype.review_id = undefined;

/**
 * @member {String} title
 */
Review.prototype.title = undefined;

/**
 * @member {module:model/MovieId} movie_id
 */
Review.prototype.movie_id = undefined;

/**
 * @member {module:model/ShowId} show_id
 */
Review.prototype.show_id = undefined;

/**
 * @member {Number} user_id
 */
Review.prototype.user_id = undefined;

/**
 * @member {Object.<String, Boolean>} likes
 */
Review.prototype.likes = undefined;

/**
 * @member {Number} rating
 */
Review.prototype.rating = undefined;

/**
 * @member {String} content
 */
Review.prototype.content = undefined;

/**
 * @member {Date} creation_time
 */
Review.prototype.creation_time = undefined;

