/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserIdBioBody model module.
 * @module model/UserIdBioBody
 * @version 3.0.0
 */
export class UserIdBioBody {
  /**
   * Constructs a new <code>UserIdBioBody</code>.
   * @alias module:model/UserIdBioBody
   * @class
   * @param bio {String} 
   */
  constructor(bio) {
    this.bio = bio;
  }

  /**
   * Constructs a <code>UserIdBioBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserIdBioBody} obj Optional instance to populate.
   * @return {module:model/UserIdBioBody} The populated <code>UserIdBioBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserIdBioBody();
      if (data.hasOwnProperty('bio'))
        obj.bio = ApiClient.convertToType(data['bio'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} bio
 */
UserIdBioBody.prototype.bio = undefined;

