/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserIdPfpBody model module.
 * @module model/UserIdPfpBody
 * @version 3.0.0
 */
export class UserIdPfpBody {
  /**
   * Constructs a new <code>UserIdPfpBody</code>.
   * @alias module:model/UserIdPfpBody
   * @class
   * @param pfp {String} 
   */
  constructor(pfp) {
    this.pfp = pfp;
  }

  /**
   * Constructs a <code>UserIdPfpBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserIdPfpBody} obj Optional instance to populate.
   * @return {module:model/UserIdPfpBody} The populated <code>UserIdPfpBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserIdPfpBody();
      if (data.hasOwnProperty('pfp'))
        obj.pfp = ApiClient.convertToType(data['pfp'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} pfp
 */
UserIdPfpBody.prototype.pfp = undefined;

