/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserIdInterestsBody model module.
 * @module model/UserIdInterestsBody
 * @version 3.0.0
 */
export class UserIdInterestsBody {
  /**
   * Constructs a new <code>UserIdInterestsBody</code>.
   * @alias module:model/UserIdInterestsBody
   * @class
   * @param interests {Array.<String>} 
   */
  constructor(interests) {
    this.interests = interests;
  }

  /**
   * Constructs a <code>UserIdInterestsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserIdInterestsBody} obj Optional instance to populate.
   * @return {module:model/UserIdInterestsBody} The populated <code>UserIdInterestsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserIdInterestsBody();
      if (data.hasOwnProperty('interests'))
        obj.interests = ApiClient.convertToType(data['interests'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} interests
 */
UserIdInterestsBody.prototype.interests = undefined;

