/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ShowId model module.
 * @module model/ShowId
 * @version 3.0.0
 */
export class ShowId {
  /**
   * Constructs a new <code>ShowId</code>.
   * @alias module:model/ShowId
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ShowId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShowId} obj Optional instance to populate.
   * @return {module:model/ShowId} The populated <code>ShowId</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShowId();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ShowId.prototype.id = undefined;

