/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Movie} from './Movie';
import {Tvshow} from './Tvshow';

/**
 * The Title model module.
 * @module model/Title
 * @version 3.0.0
 */
export class Title {
  /**
   * Constructs a new <code>Title</code>.
   * @alias module:model/Title
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Title</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Title} obj Optional instance to populate.
   * @return {module:model/Title} The populated <code>Title</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Title();
      if (data.hasOwnProperty('movie'))
        obj.movie = Movie.constructFromObject(data['movie']);
      if (data.hasOwnProperty('tvshow'))
        obj.tvshow = Tvshow.constructFromObject(data['tvshow']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Movie} movie
 */
Title.prototype.movie = undefined;

/**
 * @member {module:model/Tvshow} tvshow
 */
Title.prototype.tvshow = undefined;

