# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from base_model_ import Model
from movie_id import MovieId  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class Movie(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, movie_id: MovieId = None, title: str = None, cast: List[str] = None, director: str = None, writer: str = None, rating: float = None, genres: List[str] = None, release_date: date = None, duration: str = None, poster: str = None):  # noqa: E501
        """Movie - a model defined in Swagger

        :param movie_id: The movie_id of this Movie.  # noqa: E501
        :type movie_id: MovieId
        :param title: The title of this Movie.  # noqa: E501
        :type title: str
        :param cast: The cast of this Movie.  # noqa: E501
        :type cast: List[str]
        :param director: The director of this Movie.  # noqa: E501
        :type director: str
        :param writer: The writer of this Movie.  # noqa: E501
        :type writer: str
        :param rating: The rating of this Movie.  # noqa: E501
        :type rating: float
        :param genres: The genres of this Movie.  # noqa: E501
        :type genres: List[str]
        :param release_date: The release_date of this Movie.  # noqa: E501
        :type release_date: date
        :param duration: The duration of this Movie.  # noqa: E501
        :type duration: str
        :param poster: The poster of this Movie.  # noqa: E501
        :type poster: str
        """
        self.swagger_types = {
            'movie_id': MovieId,
            'title': str,
            'cast': List[str],
            'director': str,
            'writer': str,
            'rating': float,
            'genres': List[str],
            'release_date': date,
            'duration': str,
            'poster': str
        }

        self.attribute_map = {
            'movie_id': 'movie_id',
            'title': 'title',
            'cast': 'cast',
            'director': 'director',
            'writer': 'writer',
            'rating': 'rating',
            'genres': 'genres',
            'release_date': 'release_date',
            'duration': 'duration',
            'poster': 'poster'
        }
        self._movie_id = movie_id
        self._title = title
        self._cast = cast
        self._director = director
        self._writer = writer
        self._rating = rating
        self._genres = genres
        self._release_date = release_date
        self._duration = duration
        self._poster = poster

    @classmethod
    def from_dict(cls, dikt) -> 'Movie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The movie of this Movie.  # noqa: E501
        :rtype: Movie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def movie_id(self) -> MovieId:
        """Gets the movie_id of this Movie.


        :return: The movie_id of this Movie.
        :rtype: MovieId
        """
        return self._movie_id

    @movie_id.setter
    def movie_id(self, movie_id: MovieId):
        """Sets the movie_id of this Movie.


        :param movie_id: The movie_id of this Movie.
        :type movie_id: MovieId
        """

        self._movie_id = movie_id

    @property
    def title(self) -> str:
        """Gets the title of this Movie.


        :return: The title of this Movie.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Movie.


        :param title: The title of this Movie.
        :type title: str
        """

        self._title = title

    @property
    def cast(self) -> List[str]:
        """Gets the cast of this Movie.


        :return: The cast of this Movie.
        :rtype: List[str]
        """
        return self._cast

    @cast.setter
    def cast(self, cast: List[str]):
        """Sets the cast of this Movie.


        :param cast: The cast of this Movie.
        :type cast: List[str]
        """

        self._cast = cast

    @property
    def director(self) -> str:
        """Gets the director of this Movie.


        :return: The director of this Movie.
        :rtype: str
        """
        return self._director

    @director.setter
    def director(self, director: str):
        """Sets the director of this Movie.


        :param director: The director of this Movie.
        :type director: str
        """

        self._director = director

    @property
    def writer(self) -> str:
        """Gets the writer of this Movie.


        :return: The writer of this Movie.
        :rtype: str
        """
        return self._writer

    @writer.setter
    def writer(self, writer: str):
        """Sets the writer of this Movie.


        :param writer: The writer of this Movie.
        :type writer: str
        """

        self._writer = writer

    @property
    def rating(self) -> float:
        """Gets the rating of this Movie.


        :return: The rating of this Movie.
        :rtype: float
        """
        return self._rating

    @rating.setter
    def rating(self, rating: float):
        """Sets the rating of this Movie.


        :param rating: The rating of this Movie.
        :type rating: float
        """

        self._rating = rating

    @property
    def genres(self) -> List[str]:
        """Gets the genres of this Movie.


        :return: The genres of this Movie.
        :rtype: List[str]
        """
        return self._genres

    @genres.setter
    def genres(self, genres: List[str]):
        """Sets the genres of this Movie.


        :param genres: The genres of this Movie.
        :type genres: List[str]
        """

        self._genres = genres

    @property
    def release_date(self) -> date:
        """Gets the release_date of this Movie.


        :return: The release_date of this Movie.
        :rtype: date
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date: date):
        """Sets the release_date of this Movie.


        :param release_date: The release_date of this Movie.
        :type release_date: date
        """

        self._release_date = release_date

    @property
    def duration(self) -> str:
        """Gets the duration of this Movie.


        :return: The duration of this Movie.
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration: str):
        """Sets the duration of this Movie.


        :param duration: The duration of this Movie.
        :type duration: str
        """

        self._duration = duration

    @property
    def poster(self) -> str:
        """Gets the poster of this Movie.


        :return: The poster of this Movie.
        :rtype: str
        """
        return self._poster

    @poster.setter
    def poster(self, poster: str):
        """Sets the poster of this Movie.


        :param poster: The poster of this Movie.
        :type poster: str
        """

        self._poster = poster
