# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ShowId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, show_id: int = None):  # noqa: E501
        """ShowId - a model defined in Swagger

        :param show_id: The show_id of this ShowId.
        :type show_id: int
        """
        self.swagger_types = {
            'show_id': int
        }

        self.attribute_map = {
            'show_id': 'show_id'
        }

        self._show_id = show_id

    @property
    def show_id(self) -> int:
        """Gets the show_id of this ShowId.

        :return: The show_id of this ShowId.
        :rtype: int
        """
        return self._show_id

    @show_id.setter
    def show_id(self, show_id: int):
        """Sets the show_id of this ShowId.

        :param show_id: The show_id of this ShowId.
        :type show_id: int
        """
        self._show_id = show_id

    @classmethod
    def from_dict(cls, dikt) -> 'ShowId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The show_id of this ShowId.
        :rtype: ShowId
        """
        return util.deserialize_model(dikt, cls)
