# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.show_id import ShowId  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class Tvshow(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, show_id: ShowId=None, title: str=None, plot: str=None, season: int=None, cast: List[str]=None, director: str=None, writer: str=None, rating: float=None, genres: List[str]=None, release_date: date=None, duration: str=None, poster: str=None):  # noqa: E501
        """Tvshow - a model defined in Swagger

        :param show_id: The show_id of this Tvshow.  # noqa: E501
        :type show_id: ShowId
        :param title: The title of this Tvshow.  # noqa: E501
        :type title: str
        :param plot: The plot of this Tvshow.  # noqa: E501
        :type plot: str
        :param season: The season of this Tvshow.  # noqa: E501
        :type season: int
        :param cast: The cast of this Tvshow.  # noqa: E501
        :type cast: List[str]
        :param director: The director of this Tvshow.  # noqa: E501
        :type director: str
        :param writer: The writer of this Tvshow.  # noqa: E501
        :type writer: str
        :param rating: The rating of this Tvshow.  # noqa: E501
        :type rating: float
        :param genres: The genres of this Tvshow.  # noqa: E501
        :type genres: List[str]
        :param release_date: The release_date of this Tvshow.  # noqa: E501
        :type release_date: date
        :param duration: The duration of this Tvshow.  # noqa: E501
        :type duration: str
        :param poster: The poster of this Tvshow.  # noqa: E501
        :type poster: str
        """
        self.swagger_types = {
            'show_id': ShowId,
            'title': str,
            'plot': str,
            'season': int,
            'cast': List[str],
            'director': str,
            'writer': str,
            'rating': float,
            'genres': List[str],
            'release_date': date,
            'duration': str,
            'poster': str
        }

        self.attribute_map = {
            'show_id': 'show_id',
            'title': 'title',
            'plot': 'plot',
            'season': 'season',
            'cast': 'cast',
            'director': 'director',
            'writer': 'writer',
            'rating': 'rating',
            'genres': 'genres',
            'release_date': 'release_date',
            'duration': 'duration',
            'poster': 'poster'
        }
        self._show_id = show_id
        self._title = title
        self._plot = plot
        self._season = season
        self._cast = cast
        self._director = director
        self._writer = writer
        self._rating = rating
        self._genres = genres
        self._release_date = release_date
        self._duration = duration
        self._poster = poster

    @classmethod
    def from_dict(cls, dikt) -> 'Tvshow':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The tvshow of this Tvshow.  # noqa: E501
        :rtype: Tvshow
        """
        return util.deserialize_model(dikt, cls)

    @property
    def show_id(self) -> ShowId:
        """Gets the show_id of this Tvshow.


        :return: The show_id of this Tvshow.
        :rtype: ShowId
        """
        return self._show_id

    @show_id.setter
    def show_id(self, show_id: ShowId):
        """Sets the show_id of this Tvshow.


        :param show_id: The show_id of this Tvshow.
        :type show_id: ShowId
        """

        self._show_id = show_id

    @property
    def title(self) -> str:
        """Gets the title of this Tvshow.


        :return: The title of this Tvshow.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Tvshow.


        :param title: The title of this Tvshow.
        :type title: str
        """

        self._title = title

    @property
    def plot(self) -> str:
        """Gets the plot of this Tvshow.


        :return: The plot of this Tvshow.
        :rtype: str
        """
        return self._plot

    @plot.setter
    def plot(self, plot: str):
        """Sets the plot of this Tvshow.


        :param plot: The plot of this Tvshow.
        :type plot: str
        """

        self._plot = plot

    @property
    def season(self) -> int:
        """Gets the season of this Tvshow.


        :return: The season of this Tvshow.
        :rtype: int
        """
        return self._season

    @season.setter
    def season(self, season: int):
        """Sets the season of this Tvshow.


        :param season: The season of this Tvshow.
        :type season: int
        """

        self._season = season

    @property
    def cast(self) -> List[str]:
        """Gets the cast of this Tvshow.


        :return: The cast of this Tvshow.
        :rtype: List[str]
        """
        return self._cast

    @cast.setter
    def cast(self, cast: List[str]):
        """Sets the cast of this Tvshow.


        :param cast: The cast of this Tvshow.
        :type cast: List[str]
        """

        self._cast = cast

    @property
    def director(self) -> str:
        """Gets the director of this Tvshow.


        :return: The director of this Tvshow.
        :rtype: str
        """
        return self._director

    @director.setter
    def director(self, director: str):
        """Sets the director of this Tvshow.


        :param director: The director of this Tvshow.
        :type director: str
        """

        self._director = director

    @property
    def writer(self) -> str:
        """Gets the writer of this Tvshow.


        :return: The writer of this Tvshow.
        :rtype: str
        """
        return self._writer

    @writer.setter
    def writer(self, writer: str):
        """Sets the writer of this Tvshow.


        :param writer: The writer of this Tvshow.
        :type writer: str
        """

        self._writer = writer

    @property
    def rating(self) -> float:
        """Gets the rating of this Tvshow.


        :return: The rating of this Tvshow.
        :rtype: float
        """
        return self._rating

    @rating.setter
    def rating(self, rating: float):
        """Sets the rating of this Tvshow.


        :param rating: The rating of this Tvshow.
        :type rating: float
        """

        self._rating = rating

    @property
    def genres(self) -> List[str]:
        """Gets the genres of this Tvshow.


        :return: The genres of this Tvshow.
        :rtype: List[str]
        """
        return self._genres

    @genres.setter
    def genres(self, genres: List[str]):
        """Sets the genres of this Tvshow.


        :param genres: The genres of this Tvshow.
        :type genres: List[str]
        """

        self._genres = genres

    @property
    def release_date(self) -> date:
        """Gets the release_date of this Tvshow.


        :return: The release_date of this Tvshow.
        :rtype: date
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date: date):
        """Sets the release_date of this Tvshow.


        :param release_date: The release_date of this Tvshow.
        :type release_date: date
        """

        self._release_date = release_date

    @property
    def duration(self) -> str:
        """Gets the duration of this Tvshow.


        :return: The duration of this Tvshow.
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration: str):
        """Sets the duration of this Tvshow.


        :param duration: The duration of this Tvshow.
        :type duration: str
        """

        self._duration = duration

    @property
    def poster(self) -> str:
        """Gets the poster of this Tvshow.


        :return: The poster of this Tvshow.
        :rtype: str
        """
        return self._poster

    @poster.setter
    def poster(self, poster: str):
        """Sets the poster of this Tvshow.


        :param poster: The poster of this Tvshow.
        :type poster: str
        """

        self._poster = poster
