/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ShowId} from './ShowId';

/**
 * The Tvshow model module.
 * @module model/Tvshow
 * @version 3.0.0
 */
export class Tvshow {
  /**
   * Constructs a new <code>Tvshow</code>.
   * @alias module:model/Tvshow
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Tvshow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tvshow} obj Optional instance to populate.
   * @return {module:model/Tvshow} The populated <code>Tvshow</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Tvshow();
      if (data.hasOwnProperty('show_id'))
        obj.showId = ShowId.constructFromObject(data['show_id']);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('plot'))
        obj.plot = ApiClient.convertToType(data['plot'], 'String');
      if (data.hasOwnProperty('season'))
        obj.season = ApiClient.convertToType(data['season'], 'Number');
      if (data.hasOwnProperty('cast'))
        obj.cast = ApiClient.convertToType(data['cast'], ['String']);
      if (data.hasOwnProperty('director'))
        obj.director = ApiClient.convertToType(data['director'], 'String');
      if (data.hasOwnProperty('writer'))
        obj.writer = ApiClient.convertToType(data['writer'], 'String');
      if (data.hasOwnProperty('rating'))
        obj.rating = ApiClient.convertToType(data['rating'], 'Number');
      if (data.hasOwnProperty('genres'))
        obj.genres = ApiClient.convertToType(data['genres'], ['String']);
      if (data.hasOwnProperty('release_date'))
        obj.releaseDate = ApiClient.convertToType(data['release_date'], 'Date');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'String');
      if (data.hasOwnProperty('poster'))
        obj.poster = ApiClient.convertToType(data['poster'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ShowId} showId
 */
Tvshow.prototype.showId = undefined;

/**
 * @member {String} title
 */
Tvshow.prototype.title = undefined;

/**
 * @member {String} plot
 */
Tvshow.prototype.plot = undefined;

/**
 * @member {Number} season
 */
Tvshow.prototype.season = undefined;

/**
 * @member {Array.<String>} cast
 */
Tvshow.prototype.cast = undefined;

/**
 * @member {String} director
 */
Tvshow.prototype.director = undefined;

/**
 * @member {String} writer
 */
Tvshow.prototype.writer = undefined;

/**
 * @member {Number} rating
 */
Tvshow.prototype.rating = undefined;

/**
 * @member {Array.<String>} genres
 */
Tvshow.prototype.genres = undefined;

/**
 * @member {Date} releaseDate
 */
Tvshow.prototype.releaseDate = undefined;

/**
 * @member {String} duration
 */
Tvshow.prototype.duration = undefined;

/**
 * @member {String} poster
 */
Tvshow.prototype.poster = undefined;

