/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserSignupBody model module.
 * @module model/UserSignupBody
 * @version 3.0.0
 */
export class UserSignupBody {
  /**
   * Constructs a new <code>UserSignupBody</code>.
   * @alias module:model/UserSignupBody
   * @class
   * @param username {String} 
   * @param password {String} 
   * @param confirm_password {String} 
   * @param pfp {String} 
   * @param bio {String} 
   * @param interests {Array.<String>} 
   */
  constructor(username, password, confirm_password, pfp, bio, interests) {
    this.username = username;
    this.password = password;
    this.confirm_password = confirm_password;
    this.pfp = pfp;
    this.bio = bio;
    this.interests = interests;
  }

  /**
   * Constructs a <code>UserSignupBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserSignupBody} obj Optional instance to populate.
   * @return {module:model/UserSignupBody} The populated <code>UserSignupBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserSignupBody();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('confirm_password'))
        obj.confirm_password = ApiClient.convertToType(data['confirm_password'], 'String');
      if (data.hasOwnProperty('pfp'))
        obj.pfp = ApiClient.convertToType(data['pfp'], 'String');
      if (data.hasOwnProperty('bio'))
        obj.bio = ApiClient.convertToType(data['bio'], 'String');
      if (data.hasOwnProperty('interests'))
        obj.interests = ApiClient.convertToType(data['interests'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
UserSignupBody.prototype.username = undefined;

/**
 * @member {String} password
 */
UserSignupBody.prototype.password = undefined;

/**
 * @member {String} confirm_password
 */
UserSignupBody.prototype.confirm_password = undefined;

/**
 * @member {String} pfp
 */
UserSignupBody.prototype.pfp = undefined;

/**
 * @member {String} bio
 */
UserSignupBody.prototype.bio = undefined;

/**
 * @member {Array.<String>} interests
 */
UserSignupBody.prototype.interests = undefined;

