/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 3.0.0
 */
export class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('user_id'))
        obj.user_id = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('bio'))
        obj.bio = ApiClient.convertToType(data['bio'], 'String');
      if (data.hasOwnProperty('pfp'))
        obj.pfp = ApiClient.convertToType(data['pfp'], 'String');
      if (data.hasOwnProperty('watchlist_movies'))
        obj.watchlist_movies = ApiClient.convertToType(data['watchlist_movies'], {'String': 'Boolean'});
      if (data.hasOwnProperty('watchlist_shows'))
        obj.watchlist_shows = ApiClient.convertToType(data['watchlist_shows'], {'String': 'Boolean'});
      if (data.hasOwnProperty('interests'))
        obj.interests = ApiClient.convertToType(data['interests'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Number} user_id
 */
User.prototype.user_id = undefined;

/**
 * @member {String} username
 */
User.prototype.username = undefined;

/**
 * @member {String} password
 */
User.prototype.password = undefined;

/**
 * @member {String} bio
 */
User.prototype.bio = undefined;

/**
 * @member {String} pfp
 */
User.prototype.pfp = undefined;

/**
 * @member {Object.<String, Boolean>} watchlist_movies
 */
User.prototype.watchlist_movies = undefined;

/**
 * @member {Object.<String, Boolean>} watchlist_shows
 */
User.prototype.watchlist_shows = undefined;

/**
 * @member {Array.<String>} interests
 */
User.prototype.interests = undefined;

