/*
 * FMD
 * A website for movies' and TV shows' reviews
 *
 * OpenAPI spec version: 3.0.0
 * Contact: om.dehlantube@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserIdUsernameBody model module.
 * @module model/UserIdUsernameBody
 * @version 3.0.0
 */
export class UserIdUsernameBody {
  /**
   * Constructs a new <code>UserIdUsernameBody</code>.
   * @alias module:model/UserIdUsernameBody
   * @class
   * @param username {String} 
   */
  constructor(username) {
    this.username = username;
  }

  /**
   * Constructs a <code>UserIdUsernameBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserIdUsernameBody} obj Optional instance to populate.
   * @return {module:model/UserIdUsernameBody} The populated <code>UserIdUsernameBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserIdUsernameBody();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
UserIdUsernameBody.prototype.username = undefined;

